language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - pwd
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - pwd
 
# script: build.sh
script: phpunit --configuration phpunit.xml --coverage-text